### ISSUE TITLE
Intellisense not working on Visual Studio 2015 RTM 

### ISSUE THREAD

**Issue by Yip-Yip** [jmbledsoe/angularjs-visualstudio-intellisense#26]
As per the previous post $http and all my custom objects dont have inttelisense :( 

I have added a ASP.NET 5 web project and added angular and other packages via bower 

Also added and confirmed the _references in root wwwroot folder 

Only have the angular object 

I have run this up on both of my dev box's WIN 10 RC & Win 7 (vs2015) 

Just thinking about it I did upgrade both box's from RC to RTM if that may have a bearing on the problem

**Comment by Yip-Yip** [comment]
Getting a fresh copy of Win 10 VHD and will install fresh vs2015 RTM and then pull my git repo's to confirm it is not an upgrade problem

**Comment by Yip-Yip** [comment]
![7-25-2015 7-52-02 pm](https://cloud.githubusercontent.com/assets/1256215/8888953/f3cbee9a-3306-11e5-9de5-cccecf2b30c5.png)
![7-25-2015 7-52-42 pm](https://cloud.githubusercontent.com/assets/1256215/8888954/f3efb6ea-3306-11e5-938e-0cb6935db96c.png)
Error & _reference file

**Comment by jmbledsoe** [comment]
I haven't actually tested the VS Intellisense much in Visual Studio 2015. If you can create a minimal project that demonstrates the problem, I could pull it down and take a look.

You can verify that VS is finding your _references.js file in the VS options:
![image](https://cloud.githubusercontent.com/assets/776738/8889394/8c822272-32a7-11e5-84aa-fb91445c8e52.png)

**Comment by Yip-Yip** [comment]
That would be awesome :dancers: 

https://github.com/Yip-Yip/angular-intellesense

SportsStore (not SSportsSTore) and the sportsStore.js controller

**Comment by Yip-Yip** [comment]
I ran a fresh WIn 10 & VS 2015 up and no joy using the sample project I have linked to :(

I was reading ur stack discussion http://stackoverflow.com/questions/19522970/is-there-anyway-to-define-an-undefined-object-in-visual-studio-intellisense/22256208#22256208

And is there some extra metadata/process that i can add to my files to get it to work ???

**Comment by Yip-Yip** [comment]
Can you give me any guidence on what may help ..i.e multiple reference links in the headers ???

**Comment by jmbledsoe** [comment]
This is actually a straightforward issue to solve. The Intellisense engine never sees your module named "sportsStore" being created, since it is created in the app.html file in a script block:

```html
<script>
  angular.module("sportsStore", ["customFilters","cart"]);
</script>
```
The VS Intellisense engine is "executing" the code in your project in order to discover how to do code completion. It's using the _references.js file as its starting point and executing each reference from that file, in order. Since VS Intellisense never executes a line of code that creates the AngularJS module named "sportsStore", it doesn't know how to do code completion.

Move the JavaScript code above into its own JS file (let's call it "app.js") and include a reference to it in _references.js. Make sure the "app.js" reference is immediately after the "angular.js" reference, since you need it to create the module before the other script files configure it. That should resolve your issue.

**Comment by Yip-Yip** [comment]
Thank you SO much :dancers:
